#define _INC_MMSYSTEM
#include <Windows.h>
#include <cstdint>
#include <filesystem>
#include <string>

#define WIN32_LEAN_AND_MEAN
#include <wil/resource.h>
#include <wil/stl.h>
#include <wil/win32_helpers.h>
#include <windows.h>

static const std::wstring_view GAME_EXECUTABLE = L"MonsterHunterWorld.exe";
static const std::wstring_view MOD_LOADER_CORE_DLL = L"wml\\WMLCore.dll";

uint64_t pointer_table[200];

#define DECL_PROXY_FN_STUB(func, index)                   \
    extern "C" __declspec(dllexport) void func() {        \
        asm("jmp *%0\n\t" : : "m"(pointer_table[index])); \
    }

#define RESOLVE_PROXY_ADDR(func, index) \
    pointer_table[index] = (uint64_t)GetProcAddress(handle, #func);

void InitializeProxy() {
    // Load the original DLL and resolve the export addresses.

    char path[MAX_PATH];
    GetSystemDirectoryA(path, MAX_PATH);
    strcat_s(path, "\\winmm.dll");

    auto handle = LoadLibraryA(path);
    if (handle != NULL) {
        // MessageBoxA(NULL, "Loaded original winmm without loader lock issue",
        //             "ded original winmm without loader lock issue", MB_OK);

        RESOLVE_PROXY_ADDR(CloseDriver, 0)
        RESOLVE_PROXY_ADDR(DefDriverProc, 1)
        RESOLVE_PROXY_ADDR(DriverCallback, 2)
        RESOLVE_PROXY_ADDR(DrvGetModuleHandle, 3)
        RESOLVE_PROXY_ADDR(GetDriverModuleHandle, 4)
        RESOLVE_PROXY_ADDR(OpenDriver, 5)
        RESOLVE_PROXY_ADDR(PlaySound, 6)
        RESOLVE_PROXY_ADDR(PlaySoundA, 7)
        RESOLVE_PROXY_ADDR(PlaySoundW, 8)
        RESOLVE_PROXY_ADDR(SendDriverMessage, 9)
        RESOLVE_PROXY_ADDR(WOWAppExit, 10)
        RESOLVE_PROXY_ADDR(auxGetDevCapsA, 11)
        RESOLVE_PROXY_ADDR(auxGetDevCapsW, 12)
        RESOLVE_PROXY_ADDR(auxGetNumDevs, 13)
        RESOLVE_PROXY_ADDR(auxGetVolume, 14)
        RESOLVE_PROXY_ADDR(auxOutMessage, 15)
        RESOLVE_PROXY_ADDR(auxSetVolume, 16)
        RESOLVE_PROXY_ADDR(joyConfigChanged, 17)
        RESOLVE_PROXY_ADDR(joyGetDevCapsA, 18)
        RESOLVE_PROXY_ADDR(joyGetDevCapsW, 19)
        RESOLVE_PROXY_ADDR(joyGetNumDevs, 20)
        RESOLVE_PROXY_ADDR(joyGetPos, 21)
        RESOLVE_PROXY_ADDR(joyGetPosEx, 22)
        RESOLVE_PROXY_ADDR(joyGetThreshold, 23)
        RESOLVE_PROXY_ADDR(joyReleaseCapture, 24)
        RESOLVE_PROXY_ADDR(joySetCapture, 25)
        RESOLVE_PROXY_ADDR(joySetThreshold, 26)
        RESOLVE_PROXY_ADDR(mciDriverNotify, 27)
        RESOLVE_PROXY_ADDR(mciDriverYield, 28)
        RESOLVE_PROXY_ADDR(mciExecute, 29)
        RESOLVE_PROXY_ADDR(mciFreeCommandResource, 30)
        RESOLVE_PROXY_ADDR(mciGetCreatorTask, 31)
        RESOLVE_PROXY_ADDR(mciGetDeviceIDA, 32)
        RESOLVE_PROXY_ADDR(mciGetDeviceIDFromElementIDA, 33)
        RESOLVE_PROXY_ADDR(mciGetDeviceIDFromElementIDW, 34)
        RESOLVE_PROXY_ADDR(mciGetDeviceIDW, 35)
        RESOLVE_PROXY_ADDR(mciGetDriverData, 36)
        RESOLVE_PROXY_ADDR(mciGetErrorStringA, 37)
        RESOLVE_PROXY_ADDR(mciGetErrorStringW, 38)
        RESOLVE_PROXY_ADDR(mciGetYieldProc, 39)
        RESOLVE_PROXY_ADDR(mciLoadCommandResource, 40)
        RESOLVE_PROXY_ADDR(mciSendCommandA, 41)
        RESOLVE_PROXY_ADDR(mciSendCommandW, 42)
        RESOLVE_PROXY_ADDR(mciSendStringA, 43)
        RESOLVE_PROXY_ADDR(mciSendStringW, 44)
        RESOLVE_PROXY_ADDR(mciSetDriverData, 45)
        RESOLVE_PROXY_ADDR(mciSetYieldProc, 46)
        RESOLVE_PROXY_ADDR(midiConnect, 47)
        RESOLVE_PROXY_ADDR(midiDisconnect, 48)
        RESOLVE_PROXY_ADDR(midiInAddBuffer, 49)
        RESOLVE_PROXY_ADDR(midiInClose, 50)
        RESOLVE_PROXY_ADDR(midiInGetDevCapsA, 51)
        RESOLVE_PROXY_ADDR(midiInGetDevCapsW, 52)
        RESOLVE_PROXY_ADDR(midiInGetErrorTextA, 53)
        RESOLVE_PROXY_ADDR(midiInGetErrorTextW, 54)
        RESOLVE_PROXY_ADDR(midiInGetID, 55)
        RESOLVE_PROXY_ADDR(midiInGetNumDevs, 56)
        RESOLVE_PROXY_ADDR(midiInMessage, 57)
        RESOLVE_PROXY_ADDR(midiInOpen, 58)
        RESOLVE_PROXY_ADDR(midiInPrepareHeader, 59)
        RESOLVE_PROXY_ADDR(midiInReset, 60)
        RESOLVE_PROXY_ADDR(midiInStart, 61)
        RESOLVE_PROXY_ADDR(midiInStop, 62)
        RESOLVE_PROXY_ADDR(midiInUnprepareHeader, 63)
        RESOLVE_PROXY_ADDR(midiOutCacheDrumPatches, 64)
        RESOLVE_PROXY_ADDR(midiOutCachePatches, 65)
        RESOLVE_PROXY_ADDR(midiOutClose, 66)
        RESOLVE_PROXY_ADDR(midiOutGetDevCapsA, 67)
        RESOLVE_PROXY_ADDR(midiOutGetDevCapsW, 68)
        RESOLVE_PROXY_ADDR(midiOutGetErrorTextA, 69)
        RESOLVE_PROXY_ADDR(midiOutGetErrorTextW, 70)
        RESOLVE_PROXY_ADDR(midiOutGetID, 71)
        RESOLVE_PROXY_ADDR(midiOutGetNumDevs, 72)
        RESOLVE_PROXY_ADDR(midiOutGetVolume, 73)
        RESOLVE_PROXY_ADDR(midiOutLongMsg, 74)
        RESOLVE_PROXY_ADDR(midiOutMessage, 75)
        RESOLVE_PROXY_ADDR(midiOutOpen, 76)
        RESOLVE_PROXY_ADDR(midiOutPrepareHeader, 77)
        RESOLVE_PROXY_ADDR(midiOutReset, 78)
        RESOLVE_PROXY_ADDR(midiOutSetVolume, 79)
        RESOLVE_PROXY_ADDR(midiOutShortMsg, 80)
        RESOLVE_PROXY_ADDR(midiOutUnprepareHeader, 81)
        RESOLVE_PROXY_ADDR(midiStreamClose, 82)
        RESOLVE_PROXY_ADDR(midiStreamOpen, 83)
        RESOLVE_PROXY_ADDR(midiStreamOut, 84)
        RESOLVE_PROXY_ADDR(midiStreamPause, 85)
        RESOLVE_PROXY_ADDR(midiStreamPosition, 86)
        RESOLVE_PROXY_ADDR(midiStreamProperty, 87)
        RESOLVE_PROXY_ADDR(midiStreamRestart, 88)
        RESOLVE_PROXY_ADDR(midiStreamStop, 89)
        RESOLVE_PROXY_ADDR(mixerClose, 90)
        RESOLVE_PROXY_ADDR(mixerGetControlDetailsA, 91)
        RESOLVE_PROXY_ADDR(mixerGetControlDetailsW, 92)
        RESOLVE_PROXY_ADDR(mixerGetDevCapsA, 93)
        RESOLVE_PROXY_ADDR(mixerGetDevCapsW, 94)
        RESOLVE_PROXY_ADDR(mixerGetID, 95)
        RESOLVE_PROXY_ADDR(mixerGetLineControlsA, 96)
        RESOLVE_PROXY_ADDR(mixerGetLineControlsW, 97)
        RESOLVE_PROXY_ADDR(mixerGetLineInfoA, 98)
        RESOLVE_PROXY_ADDR(mixerGetLineInfoW, 99)
        RESOLVE_PROXY_ADDR(mixerGetNumDevs, 100)
        RESOLVE_PROXY_ADDR(mixerMessage, 101)
        RESOLVE_PROXY_ADDR(mixerOpen, 102)
        RESOLVE_PROXY_ADDR(mixerSetControlDetails, 103)
        RESOLVE_PROXY_ADDR(mmDrvInstall, 104)
        RESOLVE_PROXY_ADDR(mmGetCurrentTask, 105)
        RESOLVE_PROXY_ADDR(mmTaskBlock, 106)
        RESOLVE_PROXY_ADDR(mmTaskCreate, 107)
        RESOLVE_PROXY_ADDR(mmTaskSignal, 108)
        RESOLVE_PROXY_ADDR(mmTaskYield, 109)
        RESOLVE_PROXY_ADDR(mmioAdvance, 110)
        RESOLVE_PROXY_ADDR(mmioAscend, 111)
        RESOLVE_PROXY_ADDR(mmioClose, 112)
        RESOLVE_PROXY_ADDR(mmioCreateChunk, 113)
        RESOLVE_PROXY_ADDR(mmioDescend, 114)
        RESOLVE_PROXY_ADDR(mmioFlush, 115)
        RESOLVE_PROXY_ADDR(mmioGetInfo, 116)
        RESOLVE_PROXY_ADDR(mmioInstallIOProcA, 117)
        RESOLVE_PROXY_ADDR(mmioInstallIOProcW, 118)
        RESOLVE_PROXY_ADDR(mmioOpenA, 119)
        RESOLVE_PROXY_ADDR(mmioOpenW, 120)
        RESOLVE_PROXY_ADDR(mmioRead, 121)
        RESOLVE_PROXY_ADDR(mmioRenameA, 122)
        RESOLVE_PROXY_ADDR(mmioRenameW, 123)
        RESOLVE_PROXY_ADDR(mmioSeek, 124)
        RESOLVE_PROXY_ADDR(mmioSendMessage, 125)
        RESOLVE_PROXY_ADDR(mmioSetBuffer, 126)
        RESOLVE_PROXY_ADDR(mmioSetInfo, 127)
        RESOLVE_PROXY_ADDR(mmioStringToFOURCCA, 128)
        RESOLVE_PROXY_ADDR(mmioStringToFOURCCW, 129)
        RESOLVE_PROXY_ADDR(mmioWrite, 130)
        RESOLVE_PROXY_ADDR(mmsystemGetVersion, 131)
        RESOLVE_PROXY_ADDR(sndPlaySoundA, 132)
        RESOLVE_PROXY_ADDR(sndPlaySoundW, 133)
        RESOLVE_PROXY_ADDR(timeBeginPeriod, 134)
        RESOLVE_PROXY_ADDR(timeEndPeriod, 135)
        RESOLVE_PROXY_ADDR(timeGetDevCaps, 136)
        RESOLVE_PROXY_ADDR(timeGetSystemTime, 137)
        RESOLVE_PROXY_ADDR(timeGetTime, 138)
        RESOLVE_PROXY_ADDR(timeKillEvent, 139)
        RESOLVE_PROXY_ADDR(timeSetEvent, 140)
        RESOLVE_PROXY_ADDR(waveInAddBuffer, 141)
        RESOLVE_PROXY_ADDR(waveInClose, 142)
        RESOLVE_PROXY_ADDR(waveInGetDevCapsA, 143)
        RESOLVE_PROXY_ADDR(waveInGetDevCapsW, 144)
        RESOLVE_PROXY_ADDR(waveInGetErrorTextA, 145)
        RESOLVE_PROXY_ADDR(waveInGetErrorTextW, 146)
        RESOLVE_PROXY_ADDR(waveInGetID, 147)
        RESOLVE_PROXY_ADDR(waveInGetNumDevs, 148)
        RESOLVE_PROXY_ADDR(waveInGetPosition, 149)
        RESOLVE_PROXY_ADDR(waveInMessage, 150)
        RESOLVE_PROXY_ADDR(waveInOpen, 151)
        RESOLVE_PROXY_ADDR(waveInPrepareHeader, 152)
        RESOLVE_PROXY_ADDR(waveInReset, 153)
        RESOLVE_PROXY_ADDR(waveInStart, 154)
        RESOLVE_PROXY_ADDR(waveInStop, 155)
        RESOLVE_PROXY_ADDR(waveInUnprepareHeader, 156)
        RESOLVE_PROXY_ADDR(waveOutBreakLoop, 157)
        RESOLVE_PROXY_ADDR(waveOutClose, 158)
        RESOLVE_PROXY_ADDR(waveOutGetDevCapsA, 159)
        RESOLVE_PROXY_ADDR(waveOutGetDevCapsW, 160)
        RESOLVE_PROXY_ADDR(waveOutGetErrorTextA, 161)
        RESOLVE_PROXY_ADDR(waveOutGetErrorTextW, 162)
        RESOLVE_PROXY_ADDR(waveOutGetID, 163)
        RESOLVE_PROXY_ADDR(waveOutGetNumDevs, 164)
        RESOLVE_PROXY_ADDR(waveOutGetPitch, 165)
        RESOLVE_PROXY_ADDR(waveOutGetPlaybackRate, 166)
        RESOLVE_PROXY_ADDR(waveOutGetPosition, 167)
        RESOLVE_PROXY_ADDR(waveOutGetVolume, 168)
        RESOLVE_PROXY_ADDR(waveOutMessage, 169)
        RESOLVE_PROXY_ADDR(waveOutOpen, 170)
        RESOLVE_PROXY_ADDR(waveOutPause, 171)
        RESOLVE_PROXY_ADDR(waveOutPrepareHeader, 172)
        RESOLVE_PROXY_ADDR(waveOutReset, 173)
        RESOLVE_PROXY_ADDR(waveOutRestart, 174)
        RESOLVE_PROXY_ADDR(waveOutSetPitch, 175)
        RESOLVE_PROXY_ADDR(waveOutSetPlaybackRate, 176)
        RESOLVE_PROXY_ADDR(waveOutSetVolume, 177)
        RESOLVE_PROXY_ADDR(waveOutUnprepareHeader, 178)
        RESOLVE_PROXY_ADDR(waveOutWrite, 179)
    }
}

BOOL WINAPI DllMain(HINSTANCE hinstDLL, DWORD fdwReason, LPVOID lpvReserved) {
    if (fdwReason == DLL_PROCESS_ATTACH) {
        InitializeProxy();

        // Only load the the mod loader DLL if winmm.dll has been loaded into
        // the correct process.
        std::filesystem::path module{
            wil::GetModuleFileNameW<std::wstring>(nullptr)};

        if (module.filename().wstring() == GAME_EXECUTABLE) {
            LoadLibraryW(MOD_LOADER_CORE_DLL.data());
        }
    }

    return TRUE;
}

DECL_PROXY_FN_STUB(CloseDriver, 0)
DECL_PROXY_FN_STUB(DefDriverProc, 1)
DECL_PROXY_FN_STUB(DriverCallback, 2)
DECL_PROXY_FN_STUB(DrvGetModuleHandle, 3)
DECL_PROXY_FN_STUB(GetDriverModuleHandle, 4)
DECL_PROXY_FN_STUB(OpenDriver, 5)
DECL_PROXY_FN_STUB(PlaySound, 6)
DECL_PROXY_FN_STUB(PlaySoundA, 7)
DECL_PROXY_FN_STUB(PlaySoundW, 8)
DECL_PROXY_FN_STUB(SendDriverMessage, 9)
DECL_PROXY_FN_STUB(WOWAppExit, 10)
DECL_PROXY_FN_STUB(auxGetDevCapsA, 11)
DECL_PROXY_FN_STUB(auxGetDevCapsW, 12)
DECL_PROXY_FN_STUB(auxGetNumDevs, 13)
DECL_PROXY_FN_STUB(auxGetVolume, 14)
DECL_PROXY_FN_STUB(auxOutMessage, 15)
DECL_PROXY_FN_STUB(auxSetVolume, 16)
DECL_PROXY_FN_STUB(joyConfigChanged, 17)
DECL_PROXY_FN_STUB(joyGetDevCapsA, 18)
DECL_PROXY_FN_STUB(joyGetDevCapsW, 19)
DECL_PROXY_FN_STUB(joyGetNumDevs, 20)
DECL_PROXY_FN_STUB(joyGetPos, 21)
DECL_PROXY_FN_STUB(joyGetPosEx, 22)
DECL_PROXY_FN_STUB(joyGetThreshold, 23)
DECL_PROXY_FN_STUB(joyReleaseCapture, 24)
DECL_PROXY_FN_STUB(joySetCapture, 25)
DECL_PROXY_FN_STUB(joySetThreshold, 26)
DECL_PROXY_FN_STUB(mciDriverNotify, 27)
DECL_PROXY_FN_STUB(mciDriverYield, 28)
DECL_PROXY_FN_STUB(mciExecute, 29)
DECL_PROXY_FN_STUB(mciFreeCommandResource, 30)
DECL_PROXY_FN_STUB(mciGetCreatorTask, 31)
DECL_PROXY_FN_STUB(mciGetDeviceIDA, 32)
DECL_PROXY_FN_STUB(mciGetDeviceIDFromElementIDA, 33)
DECL_PROXY_FN_STUB(mciGetDeviceIDFromElementIDW, 34)
DECL_PROXY_FN_STUB(mciGetDeviceIDW, 35)
DECL_PROXY_FN_STUB(mciGetDriverData, 36)
DECL_PROXY_FN_STUB(mciGetErrorStringA, 37)
DECL_PROXY_FN_STUB(mciGetErrorStringW, 38)
DECL_PROXY_FN_STUB(mciGetYieldProc, 39)
DECL_PROXY_FN_STUB(mciLoadCommandResource, 40)
DECL_PROXY_FN_STUB(mciSendCommandA, 41)
DECL_PROXY_FN_STUB(mciSendCommandW, 42)
DECL_PROXY_FN_STUB(mciSendStringA, 43)
DECL_PROXY_FN_STUB(mciSendStringW, 44)
DECL_PROXY_FN_STUB(mciSetDriverData, 45)
DECL_PROXY_FN_STUB(mciSetYieldProc, 46)
DECL_PROXY_FN_STUB(midiConnect, 47)
DECL_PROXY_FN_STUB(midiDisconnect, 48)
DECL_PROXY_FN_STUB(midiInAddBuffer, 49)
DECL_PROXY_FN_STUB(midiInClose, 50)
DECL_PROXY_FN_STUB(midiInGetDevCapsA, 51)
DECL_PROXY_FN_STUB(midiInGetDevCapsW, 52)
DECL_PROXY_FN_STUB(midiInGetErrorTextA, 53)
DECL_PROXY_FN_STUB(midiInGetErrorTextW, 54)
DECL_PROXY_FN_STUB(midiInGetID, 55)
DECL_PROXY_FN_STUB(midiInGetNumDevs, 56)
DECL_PROXY_FN_STUB(midiInMessage, 57)
DECL_PROXY_FN_STUB(midiInOpen, 58)
DECL_PROXY_FN_STUB(midiInPrepareHeader, 59)
DECL_PROXY_FN_STUB(midiInReset, 60)
DECL_PROXY_FN_STUB(midiInStart, 61)
DECL_PROXY_FN_STUB(midiInStop, 62)
DECL_PROXY_FN_STUB(midiInUnprepareHeader, 63)
DECL_PROXY_FN_STUB(midiOutCacheDrumPatches, 64)
DECL_PROXY_FN_STUB(midiOutCachePatches, 65)
DECL_PROXY_FN_STUB(midiOutClose, 66)
DECL_PROXY_FN_STUB(midiOutGetDevCapsA, 67)
DECL_PROXY_FN_STUB(midiOutGetDevCapsW, 68)
DECL_PROXY_FN_STUB(midiOutGetErrorTextA, 69)
DECL_PROXY_FN_STUB(midiOutGetErrorTextW, 70)
DECL_PROXY_FN_STUB(midiOutGetID, 71)
DECL_PROXY_FN_STUB(midiOutGetNumDevs, 72)
DECL_PROXY_FN_STUB(midiOutGetVolume, 73)
DECL_PROXY_FN_STUB(midiOutLongMsg, 74)
DECL_PROXY_FN_STUB(midiOutMessage, 75)
DECL_PROXY_FN_STUB(midiOutOpen, 76)
DECL_PROXY_FN_STUB(midiOutPrepareHeader, 77)
DECL_PROXY_FN_STUB(midiOutReset, 78)
DECL_PROXY_FN_STUB(midiOutSetVolume, 79)
DECL_PROXY_FN_STUB(midiOutShortMsg, 80)
DECL_PROXY_FN_STUB(midiOutUnprepareHeader, 81)
DECL_PROXY_FN_STUB(midiStreamClose, 82)
DECL_PROXY_FN_STUB(midiStreamOpen, 83)
DECL_PROXY_FN_STUB(midiStreamOut, 84)
DECL_PROXY_FN_STUB(midiStreamPause, 85)
DECL_PROXY_FN_STUB(midiStreamPosition, 86)
DECL_PROXY_FN_STUB(midiStreamProperty, 87)
DECL_PROXY_FN_STUB(midiStreamRestart, 88)
DECL_PROXY_FN_STUB(midiStreamStop, 89)
DECL_PROXY_FN_STUB(mixerClose, 90)
DECL_PROXY_FN_STUB(mixerGetControlDetailsA, 91)
DECL_PROXY_FN_STUB(mixerGetControlDetailsW, 92)
DECL_PROXY_FN_STUB(mixerGetDevCapsA, 93)
DECL_PROXY_FN_STUB(mixerGetDevCapsW, 94)
DECL_PROXY_FN_STUB(mixerGetID, 95)
DECL_PROXY_FN_STUB(mixerGetLineControlsA, 96)
DECL_PROXY_FN_STUB(mixerGetLineControlsW, 97)
DECL_PROXY_FN_STUB(mixerGetLineInfoA, 98)
DECL_PROXY_FN_STUB(mixerGetLineInfoW, 99)
DECL_PROXY_FN_STUB(mixerGetNumDevs, 100)
DECL_PROXY_FN_STUB(mixerMessage, 101)
DECL_PROXY_FN_STUB(mixerOpen, 102)
DECL_PROXY_FN_STUB(mixerSetControlDetails, 103)
DECL_PROXY_FN_STUB(mmDrvInstall, 104)
DECL_PROXY_FN_STUB(mmGetCurrentTask, 105)
DECL_PROXY_FN_STUB(mmTaskBlock, 106)
DECL_PROXY_FN_STUB(mmTaskCreate, 107)
DECL_PROXY_FN_STUB(mmTaskSignal, 108)
DECL_PROXY_FN_STUB(mmTaskYield, 109)
DECL_PROXY_FN_STUB(mmioAdvance, 110)
DECL_PROXY_FN_STUB(mmioAscend, 111)
DECL_PROXY_FN_STUB(mmioClose, 112)
DECL_PROXY_FN_STUB(mmioCreateChunk, 113)
DECL_PROXY_FN_STUB(mmioDescend, 114)
DECL_PROXY_FN_STUB(mmioFlush, 115)
DECL_PROXY_FN_STUB(mmioGetInfo, 116)
DECL_PROXY_FN_STUB(mmioInstallIOProcA, 117)
DECL_PROXY_FN_STUB(mmioInstallIOProcW, 118)
DECL_PROXY_FN_STUB(mmioOpenA, 119)
DECL_PROXY_FN_STUB(mmioOpenW, 120)
DECL_PROXY_FN_STUB(mmioRead, 121)
DECL_PROXY_FN_STUB(mmioRenameA, 122)
DECL_PROXY_FN_STUB(mmioRenameW, 123)
DECL_PROXY_FN_STUB(mmioSeek, 124)
DECL_PROXY_FN_STUB(mmioSendMessage, 125)
DECL_PROXY_FN_STUB(mmioSetBuffer, 126)
DECL_PROXY_FN_STUB(mmioSetInfo, 127)
DECL_PROXY_FN_STUB(mmioStringToFOURCCA, 128)
DECL_PROXY_FN_STUB(mmioStringToFOURCCW, 129)
DECL_PROXY_FN_STUB(mmioWrite, 130)
DECL_PROXY_FN_STUB(mmsystemGetVersion, 131)
DECL_PROXY_FN_STUB(sndPlaySoundA, 132)
DECL_PROXY_FN_STUB(sndPlaySoundW, 133)
DECL_PROXY_FN_STUB(timeBeginPeriod, 134)
DECL_PROXY_FN_STUB(timeEndPeriod, 135)
DECL_PROXY_FN_STUB(timeGetDevCaps, 136)
DECL_PROXY_FN_STUB(timeGetSystemTime, 137)
DECL_PROXY_FN_STUB(timeGetTime, 138)
DECL_PROXY_FN_STUB(timeKillEvent, 139)
DECL_PROXY_FN_STUB(timeSetEvent, 140)
DECL_PROXY_FN_STUB(waveInAddBuffer, 141)
DECL_PROXY_FN_STUB(waveInClose, 142)
DECL_PROXY_FN_STUB(waveInGetDevCapsA, 143)
DECL_PROXY_FN_STUB(waveInGetDevCapsW, 144)
DECL_PROXY_FN_STUB(waveInGetErrorTextA, 145)
DECL_PROXY_FN_STUB(waveInGetErrorTextW, 146)
DECL_PROXY_FN_STUB(waveInGetID, 147)
DECL_PROXY_FN_STUB(waveInGetNumDevs, 148)
DECL_PROXY_FN_STUB(waveInGetPosition, 149)
DECL_PROXY_FN_STUB(waveInMessage, 150)
DECL_PROXY_FN_STUB(waveInOpen, 151)
DECL_PROXY_FN_STUB(waveInPrepareHeader, 152)
DECL_PROXY_FN_STUB(waveInReset, 153)
DECL_PROXY_FN_STUB(waveInStart, 154)
DECL_PROXY_FN_STUB(waveInStop, 155)
DECL_PROXY_FN_STUB(waveInUnprepareHeader, 156)
DECL_PROXY_FN_STUB(waveOutBreakLoop, 157)
DECL_PROXY_FN_STUB(waveOutClose, 158)
DECL_PROXY_FN_STUB(waveOutGetDevCapsA, 159)
DECL_PROXY_FN_STUB(waveOutGetDevCapsW, 160)
DECL_PROXY_FN_STUB(waveOutGetErrorTextA, 161)
DECL_PROXY_FN_STUB(waveOutGetErrorTextW, 162)
DECL_PROXY_FN_STUB(waveOutGetID, 163)
DECL_PROXY_FN_STUB(waveOutGetNumDevs, 164)
DECL_PROXY_FN_STUB(waveOutGetPitch, 165)
DECL_PROXY_FN_STUB(waveOutGetPlaybackRate, 166)
DECL_PROXY_FN_STUB(waveOutGetPosition, 167)
DECL_PROXY_FN_STUB(waveOutGetVolume, 168)
DECL_PROXY_FN_STUB(waveOutMessage, 169)
DECL_PROXY_FN_STUB(waveOutOpen, 170)
DECL_PROXY_FN_STUB(waveOutPause, 171)
DECL_PROXY_FN_STUB(waveOutPrepareHeader, 172)
DECL_PROXY_FN_STUB(waveOutReset, 173)
DECL_PROXY_FN_STUB(waveOutRestart, 174)
DECL_PROXY_FN_STUB(waveOutSetPitch, 175)
DECL_PROXY_FN_STUB(waveOutSetPlaybackRate, 176)
DECL_PROXY_FN_STUB(waveOutSetVolume, 177)
DECL_PROXY_FN_STUB(waveOutUnprepareHeader, 178)
DECL_PROXY_FN_STUB(waveOutWrite, 179)